### ISSUE TITLE
Bug in PreRetrieveMultipleSavedQuery

### ISSUE THREAD

**Issue by svejdo1** [santoshCRM/ViewRoleConfiguration#1]
There is a bug in PreRetrieveMultipleSavedQuery

Ref:

var conditionExpression = queryExpression.Criteria.Conditions.SingleOrDefault((ConditionExpression c) => c.AttributeName.Equals("returnedtypecode"));
tracingService.Trace("entityTypeCode : {0}", new object[] {
   conditionExpression.ToString()
});

This throws for every single query against "savedquery" entity that doesn't contain returnedtypecode in criteria.

**Comment by santoshCRM** [comment]
Hi Svejdo,
 Thanks for feedback. This plugin not support new CRM version for UCI form. So it will no longer available in Xrmtoolbox. I will remove it once got some time.
